#!/usr/bin/env bash
# display information about subdomains.

domain() {
	domain="$1"
	sub_domain="$2"

	# use dig to get info
	info=$(dig "$sub_domain"."$domain" | awk '/ANSWER SECTION:/{getline; print}' | awk '{print $4, $5}')
	echo "$info $sub_domain" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $3, $1, $2}'
}

# if number of argument is 1
if [ "$#" -eq 1 ]; then
	domain "$1" "www"
	domain "$1" "lb-01"
	domain "$1" "web-01"
	domain "$1" "web-02"

elif [ "$#" -eq 2 ]; then
	domain "$1" "$2"
fi

