#!/usr/bin/env bash
# configures ubuntu machine with requirements

apt update
apt install -y nginx
echo "Hello World!" | tee /var/www/html/index.html
ufw allow 'Nginx HTTP'
nginx -t
service nginx start
