#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
path_to_file="$1"
ip_server="$2"
username="$3"
path_ssh_privatekey="$4"

scp -o StrictHostKeyChecking=no -i "$path_ssh_privatekey" "$path_to_file" "$username@$ip_server:~/"
