#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

DB_USER="root"
DB_PASSWD="$1"

# dump all databases
mysqldump -u "$DB_USER" -p"$DB_PASSWD" --all-databases > backup.sql

# get current date
CURRENT_DATE=$(date '+%d-%m-%Y')

# CREATE RECOMMENDEED ARCHIVE FILE
TAR_FILE="$CURRENT_DATE.tar.gz"

#compress dump file to archive
tar -czvf "$TAR_FILE" backup.sql
