#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
	for pid in $pid; do
		kill -TERM "$pid"
	done
fi
