#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
#+ Your script should only display username user id
#+ Home directory path for the user

file="/etc/passwd"

while IFS=: read -r username _ userid _ _ home_dir _; do
	echo "$username:$userid:$home_dir"
done < "$file"
